version: '3.8'

services:
  api:
    build: .
    container_name: voice_api
    ports:
      - "8005:8005"
    volumes:
      - ./storage:/storage
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: